services:
  animedika:
    build:
      context: .
      dockerfile: Dockerfile
    image: animedika-final
    container_name: animedika-final-development
    ports:
      - "8080:8000"
    volumes:
      - ./:/app
    command: python -m backend.app
    restart: unless-stopped
